{
 "title": "Business Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Orders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Orders by Client",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orderCount_total{}", "legendFormat": "{{clientId}}" }
   ]
  },
  {
   "title": "Total Items by Client",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "itemCount_total", "legendFormat": "{{clientId}}" }
   ]
  },
  {
   "title": "Total Orders over Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(orderCount_total[$__rate_interval])",
     "legendFormat": "{{clientId}}"
    }
   ]
  }
 ]
}