apiVersion: 1

datasources:
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  jsonData:
    tracesToLogsV2:
      datasourceUid: loki
      spanEndTimeShift: 30m
      spanStartTimeShift: "-30m"
      filterByTraceID: true
      filterBySpanID: true
      tags: [{ key: 'service.name', value: 'job' }]
  url: http://tempo:3200
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
  apiVersion: 1
  uid: tempo
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  uid: loki
  editable: false
  apiVersion: 1
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: (?:"trace_?[iI]d"?:\s?"?(\w+))
        name: traceId
        url: '$${__value.raw}'
- name: Prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false