services:

  grafana:
    image: grafana/grafana:11.1.1
    volumes:
      - ${GRAFANA_DIR:-.}/grafana.ini:/etc/grafana/grafana.ini
      - ${GRAFANA_DIR:-.}/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  tempo:
    image: grafana/tempo:2.5.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ${GRAFANA_DIR:-.}/tempo.yaml:/etc/tempo.yaml
      - ${GRAFANA_DIR:-.}/tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      #- "55680"  # otlp grpc
      #- "55681"  # otlp http
      - "9411"   # zipkin
      - "4317"   # otlp grpc
      - "4318"   # otlp http

  prometheus:
    image: prom/prometheus:v2.53.1
    command: [ "--config.file=/etc/prometheus.yaml" ]
    volumes:
      - ${GRAFANA_DIR:-.}/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:3.1.1
    command: -config.file=/etc/loki.yaml
    volumes:
      - ${GRAFANA_DIR:-.}/loki.yaml:/etc/loki.yaml
    ports:
      - 3100:3100