services:
  newman:
    image: postman/newman:6.1.3-alpine
    command: ["--version"]
    volumes:
      - ${NEWMAN_DIR:-.}/nibble-demo-api.postman_collection.json:/etc/newman/nibble-demo-api.postman_collection.json