services:

  # API Gateway
  apig:
    # Image name
    image: nibl-apig:${SAG_VERSION}
    build:
      context: ${WM_DIR:-.}
      dockerfile: apig/Dockerfile
      args:
        TAG: ${APIG_DOCKER_TAG}
        SAG_HOME: ${SAG_HOME}
        IS_HOME: ${IS_HOME}
        APIG_IS_HOME: ${APIG_IS_HOME}

    environment:
      # Name and port of the REST interface of the Elasticsearch container.
      - apigw_elasticsearch_hosts=elasticsearch:9200
      # HTTPS enablement.
      - apigw_elasticsearch_https_enabled=false
      # Username and password for Elasticsearch. As standard leave it blank.
      - apigw_elasticsearch_http_username=
      - apigw_elasticsearch_http_password=
    # Setting for exposing ports to the outside (external port:internal port).
    ports:
      - 6660:5555  # Server port
      - 9072:9072  # UI port
      - 16033:10033  # JVM Remote Debug

    volumes:
      - apig-logs:${APIG_IS_HOME}/logs:rw

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    container_name: elasticsearch
    hostname: elasticsearch
    # Elasticsearch settings
    environment:
      # Important when you have several Elasticsearch containers. They need to be in the same network. Should be a different name than in other environments.
      - cluster.name=SAG_EventDataStore
      # The node name. Used for inital master node discovery.
      - node.name=elasticsearch
      # For discovery of all Elasticsearch containers.
      - discovery.seed_hosts=elasticsearch:9300
      # Used for cluster bootstrapping. The mentioned nodes are potential master nodes.
      - cluster.initial_master_nodes=elasticsearch
      # Reduces the amount of main memory the container is alowed to claim
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      # Run with HTTP 
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      # Settings for Nanoscope
      - "JAVA_CUSTOM_OPTS=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED  --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.logging/java.util.logging=ALL-UNNAMED --add-exports jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-opens jdk.compiler/com.sun.tools.javac=ALL-UNNAMED"

    ports:
      # REST interface
      - 9240:9200
      # Nodes communication
      - 9340:9300
    
  # Microservices Runtime
  msr:
    image: nibl-msr:${SAG_VERSION}
    build:
      context: ${WM_DIR:-.}
      dockerfile: msr/Dockerfile
      args:
        TAG: ${MSR_DOCKER_TAG}
        SAG_HOME: ${SAG_HOME}
        IS_HOME: ${IS_HOME}
    
    environment:
      - "JAVA_CUSTOM_OPTS=--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED  --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.logging/java.util.logging=ALL-UNNAMED --add-exports jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-opens jdk.compiler/com.sun.tools.javac=ALL-UNNAMED"
 
    ports:
      - "5550:5555"    # Integration Server HTTP
      - "10033:10033"  # JVM Remote Debug
    volumes:
      - msr-logs:${IS_HOME}/logs:rw

  # Universal Messaging
  um:
    image: nibl-um:${SAG_VERSION}
    build:
      context: ${WM_DIR:-.}
      dockerfile: um/Dockerfile
      args:
        TAG: ${UM_DOCKER_TAG}
    ports:
      - "9000:9000"    # UM NSP