{
 "title": "Business Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Orders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Orders by Client",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "demo_samples_orders_orderCount_total",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Total Amounts by Client",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "demo_samples_orders_orderAmount_total",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Total Items by Client",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "demo_samples_orders_itemCount_total",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Total Orders over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(demo_samples_orders_orderCount_total[$__rate_interval])",
     "legendFormat": "{{clientId}}"
    }
   ]
  }
 ]
}