{
 "title": "System Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "runtime_jvm_cpu_usage_ratio{type=\"processCpuLoad\"}",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Current CPU Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "runtime_jvm_cpu_threads{type=\"current\"}",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Gateway Memory Pools",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_runtime_jvm_memory_usage_bytes{service_name=\"apig\", type=\"heap\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "MSR Memory Pools",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_runtime_jvm_memory_usage_bytes{service_name=\"msr\", type=\"heap\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Total Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(service_name)(process_runtime_jvm_memory_usage_bytes{type=\"heap\",service_name=~\"apig|msr\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Miscellaneous",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Gateway Server Stats",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "runtime_server_stats_ratio{service_name=\"apig\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "MSR Server Stats",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "runtime_server_stats_ratio{service_name=\"msr\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Successful Traces",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(service_name)(otelscope_svcs_otel_tracesCreated_total{failed=\"false\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Traces",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(service_name)(otelscope_svcs_otel_tracesCreated_total{failed=\"true\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}